topos-protocol/topos

.github/workflows/sequencer_topos_core_contract_test.yml
crates/topos-sequencer-subnet-client/abi/ToposCore.json
crates/topos-sequencer-subnet-client/src/lib.rs
crates/topos-sequencer-subnet-runtime-proxy/tests/subnet_contract.rs

Update smart contract ABI.
Set subnet id with separate smart contract call.
Update sequencer tests to deploy ToposCoreProxy contract and use IToposCore.json interface to communicate with smart contract.
Fixes # (issue)
TP-511

fix: subnet id retrieval

---

crates/topos/src/main.rs

To be able to add custom fields to the `OTLP` logs/traces, the `TOPOS_OTLP_TAGS` variable is defined and will be read to extract those resources. The variable must contains a `,` separated list of key value `key=value`.
Fixes TP-496
- Add a new environment variable `TOPOS_OTLP_TAGS` which will be used to define custom tags
- `export TOPOS_OTLP_TAGS="environment=production,capabilities=superuser"`
- Tags are `,` separated and must have the `key=value` format

feat: add a new way to put custom labels/keyvalue into the OTLP

---

Cargo.lock
Cargo.toml

Update web3 version to fix secp256k1 dependency issue.
Fixes # (issue)
TP-513

fix: update web3 dependencies

---

README.md

chore: update badges on README

---

.github/workflows/docker_build_push.yml
.github/workflows/docker_utils.yml

Adding the `network` to default docker features and introduce a new image type `network`

build: adding docker network image

---

.github/actions/install-rust/action.yml

fix: codecov and llvm-preview

---

.github/workflows/docker_build_push.yml

Rename `e2e-k8s` repository to `tce-k8s`.
Fixes # (TOO-264)

chore: rename e2e-k8s to tce-k8s

---

Dockerfile

Add explicit references of `BUILDPLATFORM` to `FROM` statements.

chore: troubleshoot docker build

---

crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs

Updated tests to match new `ERC20Messaging` contract

fix: tests

---

Cargo.lock
crates/topos-metrics/Cargo.toml
crates/topos-metrics/src/lib.rs
crates/topos-p2p/Cargo.toml
crates/topos-p2p/src/lib.rs
crates/topos-p2p/src/runtime/handle_command.rs
crates/topos-p2p/src/runtime/handle_event/gossipsub.rs
crates/topos-tce-broadcast/Cargo.toml
crates/topos-tce-broadcast/src/double_echo/mod.rs
crates/topos-tce/Cargo.toml
crates/topos-tce/src/app_context.rs

In order to better manage the different metrics on the `topos` repo I introduce the `topos-metrics` where we'll put any shared (meaning cross crates) metrics or any helper to setup the metrics system

feat: adding topos-metrics crate

---

.github/workflows/coverage.yml
.github/workflows/docker_utils.yml
.github/workflows/grpc-client-stubs.yml
.github/workflows/quality.yml
.github/workflows/test.yml

Changing GitHub runners to larger one only for need job in order to avoid queuing.

chore: update github runners

---

.github/workflows/test.yml
crates/topos-p2p/src/tests/support/mod.rs
crates/topos-tce-api/tests/runtime.rs
crates/topos-test-sdk/src/lib.rs
crates/topos-test-sdk/src/networking/mod.rs
crates/topos-test-sdk/src/p2p/mod.rs
crates/topos-test-sdk/src/tce/public_api.rs
crates/topos/tests/tce.rs

Improving port detection and reservation for tests.

feat: adding better port detection

---

.github/workflows/docker_build_push.yml
.github/workflows/quality.yml
crates/topos-tce-broadcast/Cargo.toml
crates/topos-tce-broadcast/src/double_echo/mod.rs
crates/topos-tce-broadcast/src/tests/mod.rs
crates/topos/Cargo.toml

chore: remove direct mode

---

crates/topos-p2p/src/runtime/mod.rs
crates/topos-p2p/src/tests/dht.rs
crates/topos-p2p/src/tests/support/macros.rs
crates/topos-tce-api/src/runtime/builder.rs
crates/topos-tce-broadcast/src/double_echo/broadcast_state.rs
crates/topos-tce-broadcast/src/double_echo/broadcast_state/status.rs
crates/topos-tce-broadcast/src/double_echo/mod.rs
crates/topos-tce-broadcast/src/lib.rs
crates/topos-tce-broadcast/src/task_manager_futures/mod.rs
crates/topos-tce-broadcast/src/task_manager_futures/task.rs
crates/topos-tce-broadcast/src/tests/mod.rs
crates/topos-tce/src/app_context.rs
crates/topos-test-sdk/src/tce/protocol.rs
crates/topos-uci/src/subnet_id.rs

Move the broadcast logic to a new `BroadcastState`

feat: move broadcast logic to task state

---

crates/topos-certificate-spammer/src/config.rs
crates/topos-certificate-spammer/src/error.rs
crates/topos-certificate-spammer/src/lib.rs
crates/topos-certificate-spammer/src/utils.rs

Splitting some part of the spammer into multiple files

chore: split spammer into multiple files

---

rust-toolchain

Fixing [CVE-2023-38497](https://www.cve.org/CVERecord?id=CVE-2023-38497)

chore: upgrade mrsv

---

crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs

Updates in sequencer tests for latest smart contract initialization changes
Fixes TP-656
- [] I have added or updated tests that comprehensively prove my change is effective or that my feature works

fix: Topos Core smart contract initialization

---

README.md

Update the badge on the README

fix: fixing the MRSV

---

.github/actions/install-rust/action.yml
.github/workflows/release.yml
crates/topos/Cargo.toml

Adding a github action workflow in order to publish `topos` cli release.

feat: adding release of binaries

---

.github/workflows/release.yml

fix: typo in release workflow

---

.github/actions/install-rust/action.yml
.github/workflows/release.yml
README.md

Fix the used gh action and add slack notif

fix: update the release workflow

---

.github/workflows/docker_build_push.yml

Remove k8s end-to-end tests call.

chore: remove k8s e2e workflow call

---

Cargo.lock

Update to fix [RUSTSEC-2023-0063](https://rustsec.org/advisories/RUSTSEC-2023-0063)

fix: RUSTSEC-2023-0063

---

crates/topos-sequencer/src/app_context.rs
crates/topos-sequencer/src/lib.rs
crates/topos-tce-proxy/src/lib.rs
crates/topos-tce-proxy/src/worker.rs
crates/topos-tce-proxy/tests/tce_tests.rs

Adding some docs here and there to prove to myself that
I have understood the code.

docs: adding some docs to the tce-proxy

---

crates/topos-tce-api/src/grpc/mod.rs

Update invalid certificate error message

fix: expand submit certificate error details

---

.github/workflows/coverage.yml
.github/workflows/quality.yml
.github/workflows/test.yml

Update github actions to allow PR of PR to run tests

chore: update github actions

---

.github/workflows/docker_utils.yml

Adjust the default features for the docker workflow build.

fix: add network to default features

---

.github/workflows/coverage.yml

Update the `codecov` to use the `CODECOV_TOKEN`.

fix: update codecov token

---

Cargo.lock
crates/topos-crypto/Cargo.toml

This PR is just removing unused dependencies on `topos-crypto` crate.
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://github.com/topos-protocol/topos/assets/1394604/6c59668c-dc12-4252-864b-692da230c3be">
</picture>

chore: remove unused deps on crypto crate

---

Cargo.lock
crates/topos-tce-transport/Cargo.toml

This PR is just removing unused dependencies on `topos-tce-transport` crate.
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://github.com/topos-protocol/topos/assets/1394604/0487cdcd-66f3-4087-9bcf-fa311200e6be">
</picture>

chore: remove unused deps on tce-transport crate

---

Cargo.lock
crates/topos-p2p/Cargo.toml

This PR is just removing unused dependencies on `topos-p2p` crate.
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://github.com/topos-protocol/topos/assets/1394604/d3bd6c4d-1824-4ad5-9577-670b93ff17ba">
</picture>

chore: remove unused deps on topos-p2p crate

---

.github/workflows/doc.yml

chore: fixing typo branch doc

---

.github/workflows/doc.yml

Adding missing `protoc` to doc bulding

chore: adding missing protoc

---

.github/workflows/doc.yml

chore: adding cache

---

.github/workflows/doc.yml

chore: switch to nightly build for doc

---

tools/init.sh

Fixing the setup of docker for `sync` docker node

fix: init file for sync

---

.github/workflows/test.yml
crates/topos-tce-storage/README.md
crates/topos-tce-storage/src/epoch/mod.rs
crates/topos-tce-storage/src/index/mod.rs
crates/topos-tce-storage/src/lib.rs

Fixing doc warning and adding test actions

fix: doc building actions

---

.github/workflows/docker_build_push.yml

Enable temporary disabled front-end e2e test

chore: enable ci frontend-erc20-e2e

---

crates/topos/src/components/regtest/mod.rs
tools/docker-compose.yml

Fixes the `check` on docker `e2e`

fix: fixing the checks on docker-compose

---

crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs

This PR updates sequencer tests to match new address format

fix: update sequencer tests

---

crates/topos/src/config/tce.rs

fix: update default values for api endpoints

---

.github/workflows/release.yml

Adding the `aarch64` image for the release.

chore: adding aarch64 image

---

.github/workflows/release.yml

Switch back to `x86_64-unknown-linux-gnu` for release

chore: update release action target

---

.github/workflows/docker_build_push.yml

Run new topos integration workflow on CI for PR
Fixes TP-815

feat: run e2e topos integration workflow

---

BIG_CHANGE2

PR against a pre-release branch.

test rules

---

README.md

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please explain in detail, if applicable, which changes you performed in the PR and link them to issues. (If not applicable you can remove this whole section)
Please explain in detail which changes are breaking changes in the PR. (If not applicable you can remove this whole section)

fix: some change

---

crates/topos-metrics/src/api.rs
crates/topos-metrics/src/double_echo.rs
crates/topos-metrics/src/lib.rs
crates/topos-metrics/src/p2p.rs
crates/topos-metrics/src/storage.rs
crates/topos-sequencer-subnet-client/src/lib.rs
crates/topos-sequencer-subnet-client/src/subnet_contract.rs
crates/topos-sequencer-subnet-runtime/src/proxy.rs
crates/topos-tce-api/src/graphql/builder.rs
crates/topos-tce-api/src/stream/errors.rs
crates/topos-tce-broadcast/src/tests/mod.rs

Update sequencer smart contract dependency for `CrossSubnetMessageSent` event

fix: update smart contract event

---

.github/workflows/pr-checking.yml
.github/workflows/sequencer_topos_core_contract_test.yml

Ignore the pr-checking tests for release PR

build: ignore pr checking name for release

---

.github/workflows/coverage.yml

Remove Code coverage check on release branch

ci: disable coverage report on release branch
