.github/workflows/coverage.yml
Bring back the use of `CODECOV_TOKEN`—although the repo is publi—to prevent rate limiting errors on Github's end. These errors seem to happen when we don't use our own tokens and when codecov use their own ([source](https://github.com/codecov/codecov-action/issues/557#issuecomment-1216749652)).
- Use `CODECOV_TOKEN` from secrets in the `coverage.yml` CI workflow
=> chore: bring back codecov token

.github/workflows/docker_build_push.yml, .github/workflows/docker_utils.yml
This PR slightly changes the behavior of the `k8s_e2e` step of `Docker_build_push` workflow. Instead of asynchronously executing `k8s-e2e`, we trigger and wait the results of the workflow.
The trigger and wait feature is added by the `convictional/trigger-workflow-and-wait` GitHub action. Waiting for the results of `k8s-e2e` allows us to create a chain of events based on success/failure of e2e tests.
=> chore: trigger workflow and wait

Dockerfile
- mount secret for `cargo install `
This aims to fix errors such as:
https://github.com/topos-network/topos/actions/runs/4488813780/jobs/7893871473
=> chore: mount secret

.github/workflows/docker_build_push.yml
Trigger `Docker_build_push` on push to `debug/**` branches.
Created a branch `debug/test-debug-trigger` and verified that the job is triggered:
https://github.com/topos-network/topos/actions/runs/4489864527
=> chore: trigger on push to debug branches

Cargo.lock, crates/topos-sequencer-subnet-runtime-proxy/Cargo.toml, crates/topos-sequencer-subnet-runtime-proxy/src/subnet_runtime_proxy.rs, crates/topos-sequencer-subnet-runtime-proxy/tests/subnet_contract.rs, crates/topos-sequencer-tce-proxy/Cargo.toml, crates/topos-sequencer-tce-proxy/src/lib.rs, crates/topos-sequencer-types/src/lib.rs, crates/topos-sequencer/Cargo.toml, crates/topos-sequencer/src/app_context.rs
Add instrumentation event `PushCertificate`, to mark the submit of the certificate from sequencer to target subnet smart contract.
Fixes TP-327
=> feat: add push certificate instrumentation event

.github/workflows/sequencer_topos_core_contract_test.yml
The `sequencer` workflow is using an outdated `nightly` version.
=> fix: remove the fixed verion of sequencer tests

crates/topos-sequencer-tce-proxy/Cargo.toml, crates/topos-sequencer-tce-proxy/src/lib.rs
Fix for get last pending certificates
Fixes TP-508
=> fix: base64 encoding for get last pending certificates

crates/topos-p2p/src/client.rs, crates/topos-p2p/src/runtime/mod.rs, crates/topos-p2p/tests/dialling.rs, crates/topos-tce-broadcast/src/double_echo/mod.rs, crates/topos-tce-broadcast/src/lib.rs, crates/topos-tce-broadcast/src/sampler/mod.rs, crates/topos-tce-broadcast/src/tests/mod.rs, crates/topos-tce-transport/src/lib.rs, crates/topos-tce/src/app_context.rs, crates/topos-tce/src/events.rs, crates/topos-tce/src/lib.rs, crates/topos-test-sdk/src/lib.rs, crates/topos-test-sdk/src/tce/mod.rs, crates/topos-test-sdk/src/tce/protocol.rs, crates/topos/tests/cert_delivery.rs
In order to reduce the flakiness of some tests I improved the testability of the TCE by moving some test methods but also exposed a `Receiver<Event>` for the TCE.
- The `wait_for_event` method is now part of the `test-sdk`
- The `topos_tce::AppContext` is exposing a `Receiver<Event>` that will be use to expose event to the runner.
- Removed the `timeout` of the `create_network`, replacing it by a loop over each participant, checking if they received a `StableSample`
=> feat: rename TceEvents into ProtocolEvents

crates/topos-api/proto/topos/uci/v1/certification.proto
This PR removes an unneeded keyword on one protobuf definition.
Protobuf fields are optional by default, and the keyword is unnecessary in this case.
=> fix: remove unneeded optional keyword

Dockerfile
=> feat: remove unused build steps

.github/workflows/sequencer_topos_core_contract_test.yml, Cargo.lock, Cargo.toml, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs, crates/topos-tce/src/app_context.rs, crates/topos/Cargo.toml, crates/topos/src/components/mod.rs, crates/topos/src/components/setup/commands.rs, crates/topos/src/components/setup/commands/subnet.rs, crates/topos/src/components/setup/mod.rs, crates/topos/src/components/setup/subnet/installer.rs, crates/topos/src/components/setup/subnet/mod.rs, crates/topos/src/main.rs, crates/topos/src/options.rs
Add new `topos` cli command to download and install Polygon Edge binary from Github release repository.
Fixes TP-495
Added new CLI command:
```
Install Polygon Edge node binary
Usage: topos setup subnet [OPTIONS]
Options:
--path <PATH>              Installation directory path for Polygon Edge binary. If not provided, Polygon Edge binary will be installed to the current directory [env: TOPOS_SETUP_SUBNET_PATH=] [default: .]
-v, --verbose...               Defines the verbosity level
--release <RELEASE>        Polygon Edge release version. If not provided, latest release version will be installed [env: TOPOS_SETUP_SUBNET_RELEASE=]
--repository <REPOSITORY>  Polygon Edge Github repository [env: TOPOS_SETUP_SUBNET_REPOSITORY=] [default: topos-network/polygon-edge]
--list-releases …
```
=> feat: topos setup subnet

crates/topos/Cargo.toml, crates/topos/src/components/mod.rs, crates/topos/src/components/network/commands.rs, crates/topos/src/components/sequencer/commands.rs, crates/topos/src/components/setup/commands.rs, crates/topos/src/components/subnet/commands.rs, crates/topos/src/components/subnet/commands/subnet.rs, crates/topos/src/components/subnet/mod.rs, crates/topos/src/components/tce/commands.rs, crates/topos/src/main.rs, crates/topos/src/options.rs
Add additional topos cli command `subnet run` which runs `Polygon Edge` node as a subprocess
Fixes TP-408
Polygon Edge sub-process inherits standard input and output from topos cli process. When executed, to shut it down press `ctrl+C`
```
Run Polygon Edge
Usage: topos subnet run [OPTIONS] [POLYGON_EDGE_ARGUMENTS]...
Arguments:
[POLYGON_EDGE_ARGUMENTS]...  Command line to start child process
Options:
--path <PATH>  Installation directory path for Polygon Edge binary. If not provided, Polygon Edge binary will be expected in the current directory [env: TOPOS_SUBNET_PATH=] [default: .]
-v, --verbose...   Defines the verbosity level
-h, --help         Print help
```
For example to print Polygon Edge options, execute:
```
topos subnet run -- --help
```
=> feat: run polygon edge from topos cli

crates/topos-sequencer-subnet-client/abi/IToposCore.json, crates/topos-sequencer-subnet-client/src/lib.rs, crates/topos-sequencer-subnet-client/src/subnet_contract.rs, crates/topos-sequencer-subnet-runtime/src/certification.rs
With the messaging features of `ToposCore` now extracted into a new `ToposMessaging` contract, the current logic for the sequencer process to capture events linked to cross-subnet messages must be updated.
This PR updates the sequencer so that it consumes new `CrossSubnetMessageSent` events emitted by `ToposCore`.
- Update `ToposCore` ABI
- Replace the decoding of `TokenSent` events by the one of `CrossSubnetMessageSent` events
- Update the decoding to solely decode the `targetSubnetId` field (other fields weren't used beforehand anyway)
=> feat: replace TokenSent event with CrossSubnetMessageSent

Dockerfile
At the moment, caching capabilities using [sccache with S3](https://github.com/mozilla/sccache/blob/main/docs/S3.md) are only available for the CI workflow.
With this pull request, caching for local builds will be available, similar to what is done for CI workflows. However, instead of using S3, [Docker cache mounts](https://docs.docker.com/build/cache/) are utilized to store and retrieve cached objects.
Fixes # (TOO-290)
To enable the usage of `sccache`, the argument `RUSTC_WRAPPER` needs to be set to `/usr/local/cargo/bin/sccache`:
```
$ docker build . \
--tag topos \
--progress=plain \
--build-arg TOOLCHAIN_VERSION=stable \
--build-arg FEATURES=tce,sequencer,network \
--build-arg RUSTC_WRAPPER=/usr/local/cargo/bin/sccache
```
First local build:
Build using cache:
=> chore: add cache mount for sccache

.github/workflows/grpc-client-stubs.yml, .github/workflows/test.yml, crates/topos-api/proto/package-lock.json, crates/topos-api/proto/package.json
This PR adds JavaScript client stub generation and packaging in a [@topos-network/topos-grpc-client-stub](https://www.npmjs.com/package/@topos-network/topos-grpc-client-stub) npm package.
Client stubs can then be used in web applications for interactions with the gRPC API of a `topos` node.
- Add `package.json` and `package-lock.json` files in the `proto` directory to identify and version the npm package
- Add a CI workflow to generate stubs and package them in a new package to be published
**Note: Packages are built and published on new Github `releases`. It's important to remember that the version of the package (specified in its `package.json` file) needs to be updated priori to the creation of the release on Github (otherwise package publication will fail and the release will have to …
=> ci: add new grpc js client stubs generation CI workflow

.github/workflows/sequencer_topos_core_contract_test.yml, Cargo.lock, Cargo.toml, crates/topos-sequencer-subnet-client/src/lib.rs, crates/topos-sequencer-subnet-runtime/Cargo.toml, crates/topos-sequencer-subnet-runtime/src/proxy.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs
Update all sequencer tests to use ethers.rs, completely remove web3 from dependencies.
Improve tests
Fixes TP-594
=> feat: migrate all sequencer tests to ethers

crates/topos-sequencer-subnet-client/src/lib.rs, crates/topos-sequencer-subnet-client/src/subnet_contract.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs
Implemented sequencer test with send tocken and certificate cration
Fixes TP-594
=> feat: send token sequencer test

.github/actions/install-rust/action.yml
Sccache requires a number of [env vars](https://github.com/mozilla/sccache/blob/main/docs/S3.md#s3) to be set in order to function correctly.
AWS offers different options to configure credentials. [Assuming IAM roles](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) is one of them.
In this PR the order of steps were changed to fix auth errors, such as:
```
The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential.
```
=> fix: sccache credentials

.github/workflows/grpc-client-stubs.yml, .gitignore, crates/topos-api/proto/package-lock.json, crates/topos-api/proto/package.json, crates/topos-api/proto/topos/tce/v1/synchronization.proto
#229 introduced JavaScript gRPC client stubs generation through a new CI workflow. This PR adds the generation of TypeScript typings so that TypeScript clients can better use our client stubs.
Additionally, this PR changes the npm package publication flow to the following one:
- First of all, the CI workflow will only run when
- the push on `main` contains changes to protobuf files
- the PR contains changes to protobuf files (coming from the active update or previous ones)
- On PR updates, a step will check whether the npm package version was bumped and make the job fail if not
- On merge on `main`, the `npm publish` step is run if the above was successful
Testing this new logic:
- [run](https://github.com/topos-network/topos/actions/runs/5072802220) that shows a failure because of …
=> ci: generate ts typings for grpc client stub

.github/workflows/docker_build_push.yml, .github/workflows/docker_utils.yml, Dockerfile
Docker images are only built with the default `linux/amd64` platform. This PR adds the `linux/arm64` platform to add support for arm based architectures (e.g., Apple Silicon macs).
- Specify explicitly platforms to be used as target in the docker-build-push community Github Action
- Add explicit `BUILDPLATFORM` references in Dockerfile
=> ci: build multi-platform docker images

.github/workflows/quality.yml, .github/workflows/sequencer_topos_core_contract_test.yml, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs
Sequencer smart contract integration tests require `topos-smart-contracts` build artifacts folder in the `topos` root.
Fixes TP-628
Tests would not work without artifacts folder in the `topos` root
=> chore: use filesystem abi files for smart contract tests

.github/CODEOWNERS, .github/workflows/grpc-client-stubs.yml, .github/workflows/quality.yml, .github/workflows/sequencer_topos_core_contract_test.yml, Dockerfile, README.md, crates/topos-api/proto/package-lock.json, crates/topos-api/proto/package.json, crates/topos-sequencer-subnet-client/src/subnet_contract.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs, crates/topos/src/components/setup/commands/subnet.rs, tools/docker-compose.yml
Simple changes in consequence of the organization renaming to `topos-protocol`
=> chore: rename topos-network to topos-protocol

crates/topos-tce-broadcast/src/double_echo/mod.rs, crates/topos-tce-broadcast/src/lib.rs, crates/topos-tce-broadcast/src/sampler/mod.rs, crates/topos-tce-broadcast/src/tests/mod.rs
Simple refactor to ease the split to dedicated tasks
Fixes TP-597
=> refactor: simplify the double echo state change

Cargo.lock, crates/topos-certificate-spammer/Cargo.toml, crates/topos-certificate-spammer/src/utils.rs
This PR adds a dummy way to define proof size usable in the spammer for benchmarks and tests.
It listens for a `PROOF_SIZE_KB` that will be used when generating the certificate proof as `[254u8; PROOF_SIZE]`
=> chore: adding dummy proof size for spammer

crates/topos-tce-broadcast/src/double_echo/broadcast_state.rs
Switch `SystemTime` for `Instant`, since `SystemTime` can error out and is dealing with real world times.
=> fix: use instant instead of systemtime

crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs
Fix for sequencer push certificate test - use admin key,
Fixes TP-656
=> fix: push certificate test key

.cargo/audit.toml
Ignore `RUSTSEC-2022-0093` until the bump of `libp2p-noise` and `libp2p-identity` are released
=> chore: update audit for ed25519-dalek rustsec

crates/topos-sequencer/src/lib.rs, crates/topos/src/components/node/mod.rs, crates/topos/src/components/node/services.rs, crates/topos/src/components/sequencer/mod.rs, crates/topos/src/config/base.rs, crates/topos/src/config/edge.rs, crates/topos/src/config/mod.rs, crates/topos/src/config/node.rs, crates/topos/src/config/sequencer.rs, crates/topos/src/config/tce.rs, crates/topos/src/edge/mod.rs, crates/topos/tests/config.rs
- propagate all the args for Edge
- moved to kebab-case
- prune `verifier` and `data-dir` for the sequencer configuration which are not useful anymore
- change default directory for the tce db
- rename `base_tce_api_url` to `tce-grpc-endpoint`
- renamed the subnet toml profile to edge so that it is explicit that it is about the Edge arguments
=> feat: propagate all the args for edge and update tce/sequencer config

crates/topos-p2p/src/constant.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs, crates/topos-tce/src/lib.rs, crates/topos/src/components/node/services.rs, crates/topos/src/config/genesis/mod.rs, crates/topos/src/config/genesis/tests.rs, crates/topos/src/config/tce.rs
Decouple the port for Edge and TCE bootnodes
**Important**
The port for the TCE bootnode is hardcoded to `9090` until we expose the `Multiaddr` of the TCE bootnodes properly on the genesis file aside the ones for the Edge nodes.
=> fix: port discrepencies tce/edge bootnode

crates/topos-api/src/graphql/certificate.rs, crates/topos-api/src/graphql/errors.rs, crates/topos-api/src/graphql/query.rs, crates/topos-api/src/grpc/conversions/uci/v1/uci.rs, crates/topos-tce-api/src/graphql/query.rs, crates/topos-tce-api/tests/runtime.rs, crates/topos-uci/src/certificate_id.rs, crates/topos-uci/src/lib.rs
Adding a GraphQL endpoint to fetch a single certificate by id.
```graphql
query Certificate {
certificate(certificateId: {value: "0xf6c3482c85f8110e228214837baa3aaa3cdd75428d9f3527774728c5972d5050"}) {
id
prevId
proof
signature
sourceSubnetId
stateRoot
txRootHash
receiptsRootHash
verifier
}
}
```
```json
{
"data": {
"certificate": {
"id": "0xf6c3482c85f8110e228214837baa3aaa3cdd75428d9f3527774728c5972d5050",
"prevId": "0xd892f5ac52ebce5740cb7f9fc34d3196b14fb82f9fe657c8330353950af0b3b4",
"proof": "",
"signature": "ea6288f1a26ae3dac993fdf90a3463696765c44605858e154bcc05199cd4165d6ced5d4c25fa87fed92b01da051516375e8e1b563f628bac01c645c0faa925e0",
"sourceSubnetId": "0x58ba876abdaf89c8796486923d179514afe7153f3da95bdad8f08ced777bfa4c",
"stateRoot": …
```
=> feat: adding get certificate by id graphql endpoint

crates/topos-sequencer-subnet-client/src/lib.rs, crates/topos-sequencer-subnet-client/src/subnet_contract.rs, crates/topos-sequencer-subnet-runtime/src/proxy.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs, crates/topos-sequencer/src/app_context.rs, crates/topos-tce-proxy/src/worker.rs
Sequencer now takes the position of last delivered certificate or position + pending certificate index.
It syncs fast from that block to the current subnet block height, then continues listening for new blocks every 2 seconds.
Fixes TP-686
=> feat: add sync from genesis block

crates/topos-sequencer-subnet-runtime/src/certification.rs
Fix for parsing new events
Fixes TP-692
=> fix: multiple repeated events and target subnet id

Cargo.lock, crates/topos-clock/Cargo.toml, crates/topos-clock/src/lib.rs, crates/topos-clock/src/time.rs
This PR initiates the work on the state sync by introducing a `clock` in order to follow the block production. For now we use a time based clock.
=> feat: add clock (time)

.github/workflows/docker_build_push.yml, .github/workflows/docker_utils.yml
This PR adds a CI trigger for the docker build-push workflow so that we get docker images for releases.
=> ci: run docker workflow on release

crates/topos-sequencer-subnet-runtime/src/lib.rs, crates/topos-sequencer-subnet-runtime/src/proxy.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs, crates/topos-sequencer/src/lib.rs, crates/topos/src/config/sequencer.rs
Added https support for sequencer subnet client.
Fixes TP-699
Now, `--subnet-jsonrpc-endpoint` argument could be:
- `127.0.0.1:10002` meaning sequencer will use `http://127.0.0.1:10002` and `ws://127.0.0.1:10002/ws` for jsonrpc subnet endpoint
- `http://mydomain.com:1000` meaning sequencer will use `http://mydomain.com:1000` and `ws://mydomain.com:1000/ws` for jsonrpc subnet endpoint
- `https://mydomain.com:300` meaning sequencer will use `https://mydomain.com:300` and `wss://mydomain.com:300/ws` for jsonrpc subnet endpoint
=> feat: enable https for subnet endpoint

crates/topos-sequencer-subnet-client/src/subnet_contract.rs, crates/topos-sequencer-subnet-runtime/Cargo.toml, crates/topos-sequencer-subnet-runtime/src/certification.rs, crates/topos-sequencer-subnet-runtime/src/proxy.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs, crates/topos-sequencer/src/lib.rs, crates/topos-tce-proxy/src/client.rs, crates/topos-tce-proxy/src/worker.rs
Fixed subnet sync. It now starts from genesis block 0.
New sequencer regressing test checking sync from genesis block and particular historical block.
Fixes TP-706
=> feat: fix genesis block sync and add related tests

crates/topos-api/src/grpc/conversions/shared/v1/subnet.rs, crates/topos-api/src/grpc/conversions/uci/v1/uci.rs
In order to avoid panicking when malformed certificates are pushed or failure during parsing.
=> fix: switch to safe grpc conversion for cert

crates/topos-sequencer-subnet-runtime/src/proxy.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs
Add test with multiple send token events
Fixes TP-691
=> feat: add multiple new certificate events test

crates/topos-tce-broadcast/src/lib.rs, crates/topos-tce-broadcast/src/task_manager_futures/mod.rs, crates/topos-tce-proxy/src/client.rs, crates/topos-tce-proxy/tests/tce_tests.rs, crates/topos-tce-synchronizer/src/checkpoints_collector/tests.rs
In case that `topos-tce-proxy` client fails to submit certificate to the TCE, it will retry using backoff algorith.
Fixes TP-719
=> fix: submit certificate to tce using backoff algorithm in case of error

Cargo.lock
Fix a security issue with older versions of tungstenite (DoS).
https://github.com/advisories/GHSA-9mcr-873m-xcxp
=> fix: security issue with tungstenite < 0.20.1

Cargo.lock, crates/topos-tce-proxy/Cargo.toml, crates/topos-tce-proxy/tests/tce_tests.rs, crates/topos-test-sdk/src/tce/synchronizer.rs
Add additional tests for `topos-tce-proxy` and `tce-client`.
Fixes TP-731
=> feat: tce client additional tests

crates/topos-sequencer-subnet-runtime/src/certification.rs, crates/topos-sequencer-subnet-runtime/src/lib.rs, crates/topos-sequencer-subnet-runtime/src/proxy.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs, crates/topos-sequencer/src/lib.rs, crates/topos/src/components/node/services.rs, crates/topos/src/components/sequencer/commands/run.rs, crates/topos/src/components/sequencer/mod.rs, crates/topos/src/config/sequencer.rs, crates/topos/tests/snapshots/sequencer__sequencer_help_display.snap
Add sequencer parameter `--start-block` to start syncing from particular subnet block.
Fixes TP-742
=> feat: add start block

crates/topos-crypto/src/messages.rs, crates/topos-crypto/tests/messages.rs, crates/topos-tce-broadcast/benches/task_manager.rs, crates/topos-tce-broadcast/src/tests/mod.rs, crates/topos-tce/src/lib.rs, crates/topos-test-sdk/src/tce/protocol.rs, crates/topos/src/components/tce/mod.rs, crates/topos/src/lib.rs
This PR is fixing an issue while trying to parse the private key into a `LocalWallet`, instead of trying to parse `bytes` into `ut8 str` I directly use the `bytes` to generate the `wallet`.
=> fix: private key parsing

crates/topos-api/src/grpc/conversions/uci/v1/uci.rs, crates/topos-uci/src/certificate_id.rs, crates/topos-uci/src/lib.rs, crates/topos-uci/src/subnet_id.rs
Fix certificate id conversion where `0x` start of random id was removed because it indicates hex encoded string
Fixes TP-712
=> fix: cert id and subnet id conversions

crates/topos/src/config/genesis/mod.rs
Refactor extraction of validators from the genesis file.
=> fix: extract validator pubkeys from genesis

crates/topos-api/src/graphql/errors.rs, crates/topos-tce-api/src/graphql/builder.rs, crates/topos-tce-api/src/graphql/mod.rs, crates/topos-tce-api/src/graphql/query.rs, crates/topos-tce-api/src/graphql/tests.rs, crates/topos-tce-api/src/lib.rs, crates/topos-tce-api/src/runtime/builder.rs, crates/topos-tce-api/src/runtime/commands.rs, crates/topos-tce-api/src/runtime/mod.rs, crates/topos-tce-api/src/stream/mod.rs, crates/topos-tce-api/src/stream/tests.rs
This PR is adding `GraphQL` subscriptions to the current API implementation. It introduces the basic functionality and creates the new `TransientStream` struct to manage those new streams.
=> feat: adding GraphQL Subscription

crates/topos/src/config/tce.rs
The `TceConfig` struct has default values used during deserializartion. No need to parse strings 
for that and instead we can use `const` and create the `SocketAddr`s we need straight up.
=> fix: const SocketAddrs for default values

.github/workflows/grpc-client-stubs.yml
Update Github actions `gRPC` stub to prevent false positive change detection with tests `gRPC` protobuf files.
The goal is to execute the action only when the changes contains `./crates/topos-api/**.proto`
=> test: update path for github actions stub

.github/workflows/coverage.yml, .github/workflows/docker_build_push.yml, .github/workflows/grpc-client-stubs.yml, .github/workflows/quality.yml, .github/workflows/sequencer_topos_core_contract_test.yml, .github/workflows/test.yml
Update the github actions to execute on `push: master` and `pull_request` events `[opened, synchronize, reopened, ready_for_review]`
=> test: update path for github actions execution

crates/topos-tce-broadcast/src/task_manager_futures/mod.rs, crates/topos/src/components/node/commands/up.rs, crates/topos/src/components/node/mod.rs, crates/topos/src/components/node/services.rs, crates/topos/src/config/genesis/mod.rs
For `topos node up` cli command, added flag `--external-edge-node` indicating that edge process should not be started.
Sequencer will connect to the edge node pointed by configuration
Fixes TP-741
=> feat: node flag for external edge

.github/workflows/docker_utils.yml
Adding the default features `subnet` and `node` to be able to deploy the latest state of `topos`.
=> fix: add default features for docker workflow

crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs, crates/topos-sequencer/src/lib.rs, crates/topos/src/components/node/services.rs, crates/topos/src/components/sequencer/commands/run.rs, crates/topos/src/components/sequencer/mod.rs, crates/topos/src/config/sequencer.rs, crates/topos/tests/snapshots/sequencer__sequencer_help_display.snap
Add sequencer command line argument `--subnet-websocket-endpoint` to explicitly provided subnet jsonrpc websocket endpoint. Usable when subnet endpoint could not be derived from ` http/https` endpoint in a standard way (what is done by default), e.g. when custom cloud websocket endpoints are used.
Fixes TP-749
=> feat: add dedicated websocket cli parameter

.github/workflows/coverage.yml, Cargo.lock, crates/topos-api/Cargo.toml, crates/topos-api/proto/topos/tce/v1/synchronization.proto, crates/topos-api/src/grpc/generated/topos.tce.v1.rs, crates/topos-api/src/grpc/mod.rs, crates/topos-api/tests/tce_layer.rs, crates/topos-p2p/src/behaviour.rs, crates/topos-p2p/src/network.rs, crates/topos-p2p/src/runtime/handle_event.rs
Previous PR: #331 
Next PR: #333 
This PR adds the definition of the `gRPC` synchronization protocol, which contains various structs and also service definition.
This protocol will evolve as we implement and update the different kind of synchronization.
=> feat(api/grpc): add synchronization proto

Cargo.lock, crates/topos-tce-broadcast/Cargo.toml
This PR is just removing unused dependencies on `topos-tce-broadcast` crate.
<picture>
<source media="(prefers-color-scheme: dark)" srcset="https://github.com/topos-protocol/topos/assets/1394604/711f85e4-ea0c-4888-a599-365ddb2b8889">
</picture>
=> chore: remove unused deps on broadcast crate

.github/workflows/doc.yml, crates/topos-core/Cargo.toml
Removing unneeded env for doc building
=> chore: remove unneeded env

tools/docker-compose.yml
The `GraphQL` port in the docker setup was outdated and therefore couldn't access the `GraphQL` playground anymore.
=> fix: adjust graphql port in docker setup

crates/topos/src/components/node/commands/init.rs, crates/topos/src/components/node/commands/up.rs, crates/topos/src/config/base.rs
Fixed an issue where CLI arguments from the `node init` command where not taken due to auto-rewriting of `kebab-case`.
=> fix: add kebab-case rewrite for init and up commands

Cargo.lock, crates/topos/Cargo.toml, crates/topos/src/components/node/mod.rs, crates/topos/src/components/node/services.rs, crates/topos/src/config/base.rs, crates/topos/tests/config.rs
Test cli and env paremeters for `topos node init`
Fixes TP-765
=> feat: topos node init test

crates/topos/src/components/node/mod.rs, crates/topos/src/config/genesis/mod.rs, crates/topos/src/config/genesis/tests.rs
Update `topos node up` subnet error messages.
=> fix: subnet genesis file error

Cargo.toml, crates/topos-sequencer-subnet-client/src/lib.rs, crates/topos-sequencer-subnet-runtime/src/proxy.rs
Change block retrieval from the subnet node. Use websocket stream block subscription instead of timer. 
Fixes TP-599
Old mechanism to retrieve block by number is kept for initial block sync on sequencer startup. When sync is performed, blocks are further received though block subscription stream.
=> feat: use websocket stream block listener

Cargo.lock, crates/topos/Cargo.toml, crates/topos/tests/config.rs
Added test execution `topos node up` with parameters from environment and config file.
Fixes TP-765
=> feat: test topos node up execution

crates/topos-tce-storage/src/tests/mod.rs
This PR adds a non regression test on the precedence check order of source stream certificatees
=> test: adding precedence order test

crates/topos-tce-api/tests/grpc/certificate_precedence.rs, crates/topos-tce-api/tests/grpc/mod.rs, crates/topos-tce-api/tests/runtime.rs
This PR adds tests regarding the `precedence` management and how it behaves for the API.
The context is to test which certificate is returned when call the `get_latest_pending_certificate` method when the storage contains one or more certificate in the `precedence_pool`.
=> test: adding certificate precedence ordering

crates/topos-p2p/src/behaviour/discovery.rs, crates/topos-p2p/src/command.rs, crates/topos-p2p/src/event.rs, crates/topos-p2p/src/lib.rs, crates/topos-p2p/src/network.rs, crates/topos-p2p/src/runtime/handle_command.rs, crates/topos-p2p/src/runtime/handle_event.rs, crates/topos-p2p/src/runtime/mod.rs, crates/topos-tce/src/app_context/network.rs, crates/topos/tests/config.rs
Cleanup unused dial related functionality. Removed unnecessary peer/listener tracking in p2p crate.
Fixes TP-732
=> chore: cleanup dial related functionality

Cargo.lock, crates/topos/Cargo.toml
`openssl` need to be added as `vendored` to be able to build cross compilation binary
=> chore: adding openssl as dependency

crates/topos/src/components/node/commands.rs, crates/topos/src/components/node/mod.rs, crates/topos/src/components/regtest/mod.rs, crates/topos/src/options.rs, crates/topos/src/tracing.rs, crates/topos/tests/snapshots/node__help_display.snap, crates/topos/tests/snapshots/push_certificate__help_display.snap, crates/topos/tests/snapshots/regtest__regtest_spam_help_display.snap
Add `--no-color` flag and `TOPOS_LOG_NOCOLOR` env var to disable color on the CLI
=> chore: adding no-color option to CLI

crates/topos/src/components/node/commands/init.rs, crates/topos/src/components/node/mod.rs, crates/topos/tests/config.rs
There are use cases for which we don't rely on `polygon-edge`. If we don't need it, we can run `node up --no-edge-process`. However, when creating a new `config` setup, we always assume `polygon-edge` is present. In the case of a `solo-sequencer`, we want to supply a fixed `validator.key` for example, and don't need or want `polygon-edge` in the process. 
Fixes [# (issue)](https://linear.app/toposware/issue/TP-817/give-the-option-to-run-node-init-without-polygon-edge)
Adding a `--no-edge-process` flag to `node init`.
=> feat: add no-edge-process flag to node init

crates/topos-tce-synchronizer/src/checkpoints_collector/mod.rs
During deployment we detected that some peer were not accessible leading to some method call failure on gRPC. This PR is fixing the panic.
=> chore: update SynchronizerService to remove unwrap

.cargo/audit.toml
Remove the previously ignored RUSTSEC:
- [RUSTSEC-2021-0139](https://rustsec.org/advisories/RUSTSEC-2021-0139.html)
- [RUSTSEC-2022-0061](https://rustsec.org/advisories/RUSTSEC-2022-0061.html)
- [RUSTSEC-2022-0093](https://rustsec.org/advisories/RUSTSEC-2022-0093)
- [RUSTSEC-2023-0052](https://rustsec.org/advisories/RUSTSEC-2023-0052.html)
=> chore: remove audit ignore report

crates/topos-tce-storage/src/fullnode/mod.rs, crates/topos-tce-storage/src/store.rs, crates/topos-tce-storage/src/validator/mod.rs, crates/topos-tce/src/lib.rs
This PR aims to add some extra context when node starts, mostly displaying the number of certificates synced, the pending/precedence pool certificates number.
```
INFO topos_tce: Storage initialized with 0 certificates delivered, 0 pending certificates and 0 certificates in the precedence pool
```
=> chore: adding storage context on startup

.github/workflows/coverage.yml, Cargo.lock, crates/topos-tce/Cargo.toml, crates/topos-tce/src/app_context/api.rs, crates/topos-tce/src/app_context/network.rs, crates/topos-tce/src/tests/api.rs, crates/topos-tce/src/tests/mod.rs, crates/topos-tce/src/tests/network.rs
Adds some logs to debug and understand how the node behave and what it does when receiving certificate on an inconsistent network.
=> chore: adding context to certificate broadcast

crates/topos-tce/src/app_context/network.rs
Adds some logs to debug the different messages received by a node on the different `topics`.
For each `Echo/Ready` we will have a debug information telling which validator is the source of the message, which node forwarded to us.
=> chore: adding context to p2p msg received

crates/topos-p2p/src/runtime/handle_event.rs, crates/topos-p2p/src/runtime/handle_event/peer_info.rs, crates/topos-p2p/src/runtime/mod.rs, crates/topos-tce/src/lib.rs
We saw some weird connection of one node to himself, leading to warnings. This PR aims to add some logs to find out why it is happening.
=> chore: adding context on connection to self

Cargo.lock, crates/topos/Cargo.toml, crates/topos/src/components/node/mod.rs, crates/topos/tests/config.rs, crates/topos/tests/node.rs, crates/topos/tests/utils.rs
Update the `TCE` to catch `SIGTERM` signal coming from the OS
=> chore: update signal handle by tce

crates/topos-sequencer/src/lib.rs, crates/topos-tce/src/lib.rs, crates/topos/src/components/node/mod.rs, crates/topos/src/components/node/services/process.rs, crates/topos/src/edge/mod.rs
Return topos cli exit status with respect to edge subprocess status
Fixes TP-825
=> fix: return error from subprocesses

.github/workflows/coverage.yml, crates/topos-tce-proxy/src/client.rs, crates/topos-tce-proxy/tests/tce_tests.rs, crates/topos-tce-storage/src/fullnode/locking.rs, crates/topos-tce-synchronizer/src/checkpoints_collector/tests.rs, crates/topos-tce-synchronizer/src/checkpoints_collector/tests/integration.rs, crates/topos-tce-synchronizer/src/lib.rs, crates/topos-tce/src/lib.rs, crates/topos-test-sdk/src/tce/mod.rs, crates/topos/tests/cert_delivery.rs
Fixing some clippy warnings linked to the 1.75.0
=> chore: fixing clippy warning for 1.75.0

crates/topos-sequencer-subnet-runtime/tests/common/abi.rs, crates/topos-sequencer-subnet-runtime/tests/common/mod.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs
Move `abigen` smart contracts abi generation to separate module to prevent namespace pollution and to easier/cleaner handle smart contract test changes
Fixes TP-690
=> fix: move test abi generation to separate module

.github/workflows/release.yml
This PR aims to fix the redundant notifications emitted when creating a release.
=> fix: fixing release notification

crates/topos-tce-broadcast/src/double_echo/mod.rs, crates/topos-tce-broadcast/src/task_manager/mod.rs, crates/topos-tce-broadcast/src/tests/mod.rs, crates/topos-tce-broadcast/src/tests/task_manager.rs, crates/topos-tce/src/app_context/network.rs, crates/topos-tce/src/tests/network.rs
Updating double echo for devnet debug
=> chore: updating double echo for devnet

Cargo.lock, crates/topos-sequencer-subnet-client/src/lib.rs, crates/topos-sequencer-subnet-runtime/Cargo.toml, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs
Remove polygon edge inside docker execution for sequencer tests. Use anvil binary as evm node to deploy contracts and exec
Fixes TP-773
This PR also requires change in e2e CI setup
=> feat: use anvil for sequencer tests

Cargo.lock, crates/topos-p2p/src/config.rs, crates/topos-p2p/src/network.rs, crates/topos-p2p/src/runtime/mod.rs, crates/topos-p2p/src/tests/command/random_peer.rs, crates/topos-tce-broadcast/Cargo.toml, crates/topos-tce-broadcast/src/constant.rs, crates/topos-tce-broadcast/src/double_echo/mod.rs, crates/topos-tce-broadcast/src/task_manager/mod.rs, crates/topos-tce-broadcast/src/tests/task_manager.rs, crates/topos-tce-storage/src/errors.rs, crates/topos-tce-storage/src/rocks/db_column.rs, crates/topos-tce-storage/src/rocks/map.rs, crates/topos-tce-storage/src/tests/mod.rs, crates/topos-tce-storage/src/types.rs, crates/topos-tce-storage/src/validator/mod.rs, crates/topos-tce-storage/src/validator/tables.rs, crates/topos-tce/src/app_context.rs, crates/topos-tce/src/app_context/api.rs, crates/topos-tce/src/app_context/network.rs, crates/topos-tce/src/config.rs, crates/topos-tce/src/lib.rs, crates/topos-test-sdk/src/tce/p2p.rs, crates/topos/src/components/node/services/process.rs, crates/topos/src/config/tce.rs
This PR is the final one regarding the stabilization of the `soft-fork` playbook for `devnet`.
It contains various fixes and changes that allow the network to be upgraded without the need of purging it, allowing the continuity of the delivery while upgrading. This PR biggest change is that the `broadcast` is actively asking for certificates, instead of receiving them from a channel. It allows us to stack incoming certificates in the Storage and process them at node pace. When shutting down, the broadcast will restart from the next certificate still in pending in the Storage.
- Update on the `node up` command, the parsing of the `boot_peers` from genesis is needed in order to define the `is-bootnode` config value as soon as possible.
- The `is-bootnode` is a config value but is not …
=> feat: update double echo to use pending CF

Cargo.lock
"Resource exhaustion vulnerability in h2 may lead to Denial of Service (DoS)"
Reference: https://github.com/hyperium/h2/pull/737
Fixes [RUSTSEC-2024-0003](https://rustsec.org/advisories/RUSTSEC-2024-0003.html)
=> fix: RUSTSEC-2024-0003

crates/topos-tce/src/app_context/network.rs
Fixes a missmatch between log and error expectations.
=> chore: fix logs for pending

crates/topos-tce-broadcast/src/double_echo/mod.rs, crates/topos-tce-broadcast/src/task_manager/mod.rs, crates/topos-tce-broadcast/src/tests/task_manager.rs
The broadcast on `devnet-1` was stuck after some time.
It was because an unused channel was filling up by un-consumed messages and the N+1 message was waiting for slot that was never released.
=> fix: remove an unused channel that was locking the broadcast

crates/topos-core/src/api/graphql/certificate.rs, crates/topos-core/src/api/graphql/checkpoint.rs, crates/topos-core/src/api/graphql/subnet.rs, crates/topos-tce-api/src/graphql/query.rs, crates/topos-tce-api/src/graphql/tests.rs, crates/topos-tce-api/tests/runtime.rs
Update some structs after the merge of `topos-core`, `topos-uci` and `topos-api`.
BREAKING CHANGE: This break the `0.0.10` GraphQL API definition due to the rename of some fields.
=> chore: refactor struct in topos-core

crates/topos-core/src/api/graphql/certificate.rs, crates/topos-core/src/api/graphql/checkpoint.rs, crates/topos-core/src/types.rs, crates/topos-tce-api/src/graphql/query.rs, crates/topos-tce-api/src/graphql/tests.rs, crates/topos-tce-api/src/grpc/messaging.rs, crates/topos-tce-api/src/runtime/client.rs, crates/topos-tce-api/src/runtime/commands.rs, crates/topos-tce-api/src/runtime/mod.rs, crates/topos-tce-api/src/runtime/sync_task.rs, crates/topos-tce-api/src/stream/commands.rs, crates/topos-tce-api/src/stream/mod.rs, crates/topos-tce-api/src/stream/tests.rs, crates/topos-tce-api/tests/runtime.rs, crates/topos-test-sdk/src/certificates/mod.rs
This PR adds `positions` to `Certificate` in GraphQL response.
=> feat: adding positions to certificate

Cargo.lock, crates/topos/Cargo.toml
Bump version for the `topos` crate, which should be in line with the Stack version.
=> chore: bump version for topos to 0.0.11

.github/workflows/coverage.yml
=> chore: remove mention of topos-api from coverage YAML

crates/topos-metrics/src/lib.rs, crates/topos-metrics/src/p2p.rs, crates/topos-metrics/src/tests.rs
This PR fixes a wrong configuration for the `IntCounterVec` metrics on `p2p` layer.
=> fix: fixing wrong use of IntCounterVec

crates/topos-tce-api/src/graphql/query.rs, crates/topos-tce-broadcast/src/double_echo/broadcast_state.rs, crates/topos-tce-storage/src/rocks/map.rs, crates/topos-tce-storage/src/tests/checkpoints.rs, crates/topos-tce-storage/src/tests/mod.rs, crates/topos-tce-storage/src/validator/mod.rs, crates/topos-tce-synchronizer/src/checkpoints_collector/mod.rs, crates/topos-tce-synchronizer/src/lib.rs, crates/topos/src/options/input_format.rs
This PR explores the issue with the synchronization of a new node. It solves the issue by refactoring a bit the calculation of diff between local and input.
The problem relied on the `prefix_iter_at` method that was introduced during the synchronization phase, but didn't work as expected in some cases. A ticket has been created to fix or refactor it, in the meantime, the synchronization process is falling back to the `skip` method.
=> chore: debug 0.0.11 synchronization

Cargo.lock, crates/topos-telemetry/Cargo.toml, crates/topos-telemetry/src/lib.rs, crates/topos-telemetry/src/tracing.rs, crates/topos/Cargo.toml, crates/topos/src/components/node/mod.rs, crates/topos/src/components/regtest/mod.rs, crates/topos/src/main.rs
For consistency and further use, move the otlp related configuration setup to `topos-telemetry`.
=> feat: move telemetry-otlp setup into telemetry crate

Cargo.lock, crates/topos-certificate-spammer/Cargo.toml, crates/topos-certificate-spammer/src/config.rs, crates/topos-certificate-spammer/src/error.rs, crates/topos-certificate-spammer/src/lib.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs, crates/topos/src/components/regtest/commands/spam.rs, crates/topos/src/components/regtest/mod.rs, crates/topos/tests/regtest.rs, crates/topos/tests/snapshots/regtest__regtest_spam_help_display.snap
When operating `topos` nodes in a Kubernetes environment, we have to address each service through a Kubernetes abstraction, called a `pod`. These pods are networked via `DNS`. When testing the network via `topos regtest spam` our fixed `IP_ADDRESS:PORT` approach of talking to each node doesn't work. We therefore add new flags to the command:
```
topos regtest spam --benchmark --dns "http://validator-{N}:1340" --number 10
```
Fixes [TP-852](https://linear.app/toposware/issue/TP-852/adjust-the-topos-regtest-spam-command-to-take-dns-instead-of-ip)
=> feat: add benchmark dns option to spam subcommand

Cargo.lock, Cargo.toml, crates/topos-metrics/src/storage.rs, crates/topos-sequencer-subnet-runtime/tests/subnet_contract.rs, crates/topos-tce-api/src/graphql/query.rs, crates/topos-tce-api/tests/runtime.rs, crates/topos-tce-storage/Cargo.toml, crates/topos-tce-storage/src/errors.rs, crates/topos-tce-storage/src/fullnode/mod.rs, crates/topos-tce-storage/src/rocks/db_column.rs, crates/topos-tce-storage/src/store.rs, crates/topos-tce-storage/src/tests/mod.rs, crates/topos-tce-storage/src/validator/mod.rs
This PR adds two new metrics accessible on the default port `3000` (e.g.: `localhost:3000`):
- `STORAGE_PENDING_POOL_COUNT` that tracks the number of certificates in the `pending_pool`.
- `STORAGE_PRECEDENCE_POOL_COUNT` that tracks the number of certificates in the `precedence_pool`.
:warning: Keep in my that those values are estimation based on the `rocksdb` metadata:
> Q: Why GetIntProperty can only returns an estimated number of keys in a RocksDB database?
>
> A: Obtaining an accurate number of keys in any LSM databases like RocksDB is a challenging problem as they have duplicate keys and deletion entries (i.e., tombstones) that will require a full compaction in order to get an accurate number of keys. In addition, if the RocksDB database contains merge operators, it will also make the …
=> feat: track queue size in metrics/graphql

crates/topos/src/components/setup/mod.rs, crates/topos/src/lib.rs, crates/topos/tests/setup.rs
Add more helpful CLI outputs to the `topos setup` command + tests.
Fixes [TP-863](https://linear.app/toposware/issue/TP-863/improve-output-of-the-topos-setup-command)
=> feat: add proper error handling to setup command

crates/topos-tce-broadcast/benches/task_manager.rs, crates/topos-tce-broadcast/src/double_echo/mod.rs, crates/topos-tce-broadcast/src/event.rs, crates/topos-tce-broadcast/src/lib.rs, crates/topos-tce-broadcast/src/task_manager/mod.rs, crates/topos-tce-broadcast/src/tests/mod.rs, crates/topos-tce-broadcast/src/tests/task_manager.rs, crates/topos-tce/src/app_context/protocol.rs
This PR adds a call to `get_next_pending_certificates` after a task ends in order to process next pending certificates.
It also removes some old struct/mechanism of the broadcast.
=> fix: add next_pending_certificate on end task

crates/topos-p2p/src/behaviour/gossip.rs
The initial sender is supposed to be the only one to publish the Certificate on the gossipsub topic `topos_gossip`. The initial sender is the one who receives the Certificate from the gRPC API and not from gossipsub.
The rework on the storage by moving the management of the pending and precedence pool on the storage layer introduced the loss of the origin of the Certificate (whether it is received from gossipsub or grpc), consequently, the message was pushed by everyone on the `topos_gossip` topic on both cases since this storage rework.
- Before (default config, see [here](https://docs.rs/libp2p-gossipsub/latest/libp2p_gossipsub/struct.Config.html#method.message_id))
- Author based message id: `(PeerId, nonce)`, so we had as many duplicate of Certificate as the number of peers
- After
- …
=> fix: remove duplicated certificate push on gossipsub

Cargo.lock
Fixing [RUSTSEC-2024-0019](https://rustsec.org/advisories/RUSTSEC-2024-0019.html). Windows specific, but nevertheless worth an upgrade:
> For users of Tokio, this vulnerability is serious and can result in a use-after-free in Tokio.
> The vulnerability is Windows-specific, and can only happen if you are using named pipes. Other IO resources are not affected.
=> fix: update mio

crates/topos-p2p/src/behaviour/peer_info.rs
This PR is just removing a temporary config put in place during the creation of the `soft-fork` playbook.
Removes the `with_cache_size` disabling the LRU cache of `identify` protocol.
=> chore: removing cache_size

crates/topos-config/src/genesis/mod.rs, crates/topos-config/src/genesis/tests.rs, crates/topos-config/src/node.rs, crates/topos-node/src/lib.rs, crates/topos-telemetry/src/tracing.rs, crates/topos/src/components/node/mod.rs, crates/topos/tests/config.rs
This PR updates how we deal with config and errors during the start of the node.
Basically, removing and refactoring `Config` management and responsibility of parsing, removing some `Box<dyn Error>` to proper error handling.
=> refactor: update error management and config/process

crates/topos-tce-api/src/stream/mod.rs, crates/topos-tce-api/src/stream/tests.rs
In our current setup, the `sequencer` is opening a gRPC stream to the `tce`. If successful, we send `delivered_certificates` back to the `sequencer` (or any other client). However, if `sequencer` shuts down (or restarts), the stream was not closed on the `tce` side, resulting in multiple open streams with dangling connections.
This PR is fixing this issue by handling the error cases of a streaming message.
Fixes [TP-500](https://linear.app/toposware/issue/TP-500/as-topos-i-want-to-better-manage-closed-grpc-streams-so-that-i-can)
```bash
024-02-23T15:55:02.245162Z  INFO topos_tce_api::stream: Received an OpenStream command for the stream cbb40b6a-89fc-497a-8594-fa680656bba1
2024-02-23T15:55:02.245189Z  INFO topos_tce_api::runtime: Stream cbb40b6a-89fc-497a-8594-fa680656bba1 is registered …
```
=> feat: terminate stream if client is dropping the connection

crates/topos-certificate-spammer/src/lib.rs, crates/topos-core/src/api/graphql/subnet.rs, crates/topos-p2p/src/error.rs, crates/topos-sequencer/src/app_context.rs, crates/topos-tce-broadcast/src/double_echo/broadcast_state.rs, crates/topos-tce-broadcast/src/double_echo/mod.rs, crates/topos-tce-broadcast/src/task_manager/mod.rs, crates/topos-tce-broadcast/src/task_manager/task.rs, crates/topos-tce-storage/src/validator/mod.rs, crates/topos-tce/src/app_context.rs, crates/topos-tce/src/app_context/api.rs, crates/topos-tce/src/app_context/network.rs, crates/topos-tce/src/app_context/protocol.rs, crates/topos/tests/node.rs
Simple PR to revise the level of some logs and fix some typo.
=> chore: refactor logs and fix typo

crates/topos-core/src/api/graphql/certificate.rs, crates/topos-core/src/api/graphql/checkpoint.rs, crates/topos-tce-api/src/graphql/builder.rs, crates/topos-tce-api/src/graphql/query.rs, crates/topos-tce-api/src/graphql/tests.rs, crates/topos-tce-api/src/runtime/builder.rs, crates/topos-tce-api/src/runtime/error.rs, crates/topos-tce-api/tests/runtime.rs, crates/topos-tce-broadcast/src/double_echo/mod.rs, crates/topos-tce-broadcast/src/lib.rs, crates/topos-tce-broadcast/src/task_manager/mod.rs, crates/topos-tce-broadcast/src/tests/task_manager.rs, crates/topos-tce-storage/src/client.rs, crates/topos-tce-storage/src/tests/mod.rs, crates/topos-tce-storage/src/validator/mod.rs, crates/topos-tce/src/app_context.rs, crates/topos-tce/src/app_context/api.rs, crates/topos-tce/src/app_context/network.rs, crates/topos-tce/src/lib.rs
This PR refactors a bit the workflow that trigger new certs for delivery.
It also adds new queries on GraphQL in order to extract context from nodes.
Previous refactorization introduced  `pull` mechanism on the `broadcast` where the `task` manager where actively pulling the next `certificate` from the `pending_pool`, the setup was to allow the broadcast to start consuming the `pending_pool` when ready. However, a corner case exists that this PR is solving:
- `pending_pool` checking tick is 10sec (1sec in reality) and tick at `S0`
- `certificate A` arrives on the node, is valid and can be delivered at `S2`
- ...
- `pending_pool` checking tick execute at `S10`
- `certificate A` is being broadcast
Between `S2` and `S10` the certificate is waiting in the pending_pool for nothing.
The changes …
=> refactor: improve delivery timing

crates/topos-sequencer-subnet-client/src/lib.rs, crates/topos-sequencer-subnet-client/src/subnet_contract.rs
Update smart contract `CrossSubnetMessageSent` event
Fixes TP-864
=> fix: bump smart contract version

.github/workflows/docker_build_push.yml, Cargo.lock, crates/topos-p2p/Cargo.toml, crates/topos-p2p/src/behaviour/gossip.rs, crates/topos-p2p/src/behaviour/peer_info.rs, crates/topos-p2p/src/config.rs, crates/topos-p2p/src/network.rs, crates/topos-p2p/src/runtime/handle_event.rs, crates/topos-p2p/src/runtime/handle_event/peer_info.rs, crates/topos-tce-api/src/graphql/builder.rs, crates/topos-tce-api/tests/grpc/certificate_precedence.rs, crates/topos-tce-api/tests/runtime.rs, crates/topos-tce-broadcast/benches/task_manager.rs, crates/topos-tce-broadcast/src/tests/mod.rs, crates/topos-tce-broadcast/src/tests/task.rs, crates/topos-tce-broadcast/src/tests/task_manager.rs, crates/topos-tce-storage/src/fullnode/mod.rs, crates/topos-tce-storage/src/tests/mod.rs, crates/topos-tce-storage/src/tests/pending_certificates.rs, crates/topos-tce-storage/src/validator/mod.rs, crates/topos-tce/src/app_context/api.rs, crates/topos-tce/src/app_context/network.rs, crates/topos-tce/src/lib.rs, crates/topos-test-sdk/src/crypto.rs, crates/topos-test-sdk/src/lib.rs, crates/topos-test-sdk/src/tce/mod.rs, crates/topos-test-sdk/src/tce/p2p.rs
This PR is covering a corner case which involve the delivery of a prev certificate and a child certificate.
The scenario is this one:
- A `prev` certificate (`C1`) has been delivered (by the broadcast) and need to be persisted
The persist method will hold a lock while performing multiple insert/delete to avoid
insert race condition.
- At the same time, another node is sending a certificate (`C2`) which have `C1` as `prev_id`.
`C2` is looking at the storage to find if the `prev_id` `C1` is delivered but find nothing as
the `persist` method is still working at creating the `WriteBatch`. It led the node to put
`C2` in the `precedence_pool` waiting for `C1` to be delivered while it is in fact already
delivered.
To avoid that and as a first step, when trying to insert a certificate in the …
=> fix: concurrency insert between pending and delivered

crates/topos-config/src/edge.rs, crates/topos-config/src/edge/command.rs, crates/topos-config/src/genesis/mod.rs, crates/topos-config/src/lib.rs, crates/topos-config/src/node.rs, crates/topos-node/src/lib.rs, crates/topos/src/components/node/commands.rs, crates/topos/src/components/node/commands/init.rs, crates/topos/src/components/node/commands/up.rs, crates/topos/src/components/node/mod.rs, crates/topos/tests/node.rs, crates/topos/tests/setup.rs
This PR fixes the parsing of the `edge-path` when set by env var.
It also refactors a bit how the edge binary path is created and add non regression tests.
=> fix(config): fix the parse of edge_path ENV var

crates/topos-p2p/src/behaviour.rs, crates/topos-p2p/src/behaviour/discovery.rs, crates/topos-p2p/src/runtime/handle_event.rs, crates/topos-p2p/src/runtime/handle_event/discovery.rs, crates/topos-tce-synchronizer/src/checkpoints_collector/tests/integration.rs
This PR reworks how we manage the ticks of the bootstrap queries.
After investigating an issue on `devnet` I saw that two queries were executed at the same second.
While the expected behavior is to have a delay of 60sec (by default).
```
09:33:29: DEBUG -> Started kademlia bootstrap query with query_id: QueryId(0)
^ (1) This is the first query is created when the node starts
09:33:29: INFO  -> Dialing bootpeer 16Uiu2HAmTqPREKjx7dYpcEsjByzy8yZMgjipzAcStMFQBAvZZL73 on connection: 1
^ We dial the other peer for this query
09:33:29: WARN  -> Unable to connect to bootpeer 16Uiu2HAmTqPREKjx7dYpcEsjByzy8yZMgjipzAcStMFQBAvZZL73
^ The other bootnode is not available
09:33:29: WARN  -> Bootstrap query finished but unable to connect to bootnode during initialization, switching to unhealthy and fast …
```
=> fix(p2p): rework ticks of bootstrap query interval

.github/workflows/coverage.yml, .github/workflows/docker_build_push.yml, .github/workflows/sequencer_topos_core_contract_test.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, cliff.toml, crates/topos-sequencer-subnet-client/src/subnet_contract.rs, crates/topos/Cargo.toml
The changes being made for release `v0.1.0` are exposed in the [CHANGELOG.md](https://github.com/topos-protocol/topos/blob/release/v0.1.0/CHANGELOG.md)
The version will be tested on *devnet* and on *benchmark* runs.
When the release matches the expectation those steps are needed:
=> release: v0.1.0
